name: build

on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:

jobs:
  # See https://github.com/mvdan/github-actions-golang
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['stable']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Go install moq
        run: go install

      - name: Test
        run: go test ./...

  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: golangci-lint cache
        uses: actions/cache@v4
        with:
          path: ~/go/bin/golangci-lint
          key: ${{ runner.os }}-golangci-lint-v1.54.1

      - uses: golangci/golangci-lint-action@v4
        with:
          version: "v1.54.1"
          skip-pkg-cache: true
          args: --max-same-issues=0 --out-format=tab --config=./.golangci.yml
