name: build

on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:

jobs:
  # See https://github.com/mvdan/github-actions-golang
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.18.x, 1.19.x]
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-expanding-configurations
        include:
          - os: windows-latest
            go-version: 1.19.x
          - os: macos-latest
            go-version: 1.19.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Go install moq
        run: go install

      - name: golangci-lint cache
        uses: actions/cache@v3
        with:
          path: ~/go/bin/golangci-lint
          key: ${{ runner.os }}-golangci-lint-v1.54.1

      - name: Test
        run: go test ./...

      - uses: golangci/golangci-lint-action@v4
        with:
          version: "v1.54.1"
          skip-pkg-cache: true
          args: --max-same-issues=0 --out-format=tab --config=./.golangci.yml
